# Generated by Django 4.1.5 on 2023-02-15 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Company', models.CharField(max_length=100)),
                ('Cost', models.CharField(max_length=100)),
                ('Color', models.CharField(max_length=50)),
                ('Top_Speed', models.CharField(max_length=100)),
            ],
        ),
    ]
